"""PageSnapshotter id/selector heuristics (pure, no browser needed)."""
from __future__ import annotations

from src.browser.snapshotter import PageSnapshotter


def _snap():
    return PageSnapshotter(page=None)


def test_autogenerated_ids_rejected():
    s = _snap()
    assert s._looks_autogenerated("field-x7k2p")     # digit-bearing suffix
    assert s._looks_autogenerated(":r5:")             # React useId (colon form)
    assert s._looks_autogenerated("«r5»")             # React useId (guillemet form)
    assert s._looks_autogenerated("mui-32")


def test_stable_ids_kept():
    s = _snap()
    assert not s._looks_autogenerated("firstName")
    assert not s._looks_autogenerated("payment-PaymentMethod")
    assert not s._looks_autogenerated("email_address")


def test_escape_quotes_and_backslashes():
    s = PageSnapshotter._escape('a"b\\c')
    assert s == 'a\\"b\\\\c'
