"""Diagnostic: dump what the custom MUI Select dropdowns actually look like.

The agent gives these dropdowns a fragile positional selector (because it can't
find a stable id/name it recognises), which leads to mis-fills. Before fixing the
selector we need to SEE what stable handle each dropdown really has — a hidden
field name? a real id we're wrongly discarding? a label link? This prints that.

Run:
  uv run python scripts/inspect_dropdowns.py "http://192.168.0.191:8000/accounting/cash-in/general"
"""
import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.browser.session import BrowserSession
from src.browser.snapshotter import PageSnapshotter

AUTH = "auth.json"


async def main(url: str) -> None:
    auth = AUTH if Path(AUTH).exists() else None
    async with BrowserSession(headless=True, storage_state=auth) as session:
        await session.goto(url)
        page = session.page
        combos = await page.query_selector_all(
            "[role='combobox'], [aria-haspopup='listbox']"
        )
        print(f"\nFound {len(combos)} dropdown(s) on {url}\n")

        sn = PageSnapshotter(page)
        for i, el in enumerate(combos, 1):
            info = await el.evaluate("""el => {
                const fc = el.closest('.MuiFormControl-root');
                const lbl = fc ? fc.querySelector('label, .MuiInputLabel-root') : null;
                // MUI usually renders a hidden <input> that carries the real form
                // field name — that's the stable handle we're hoping exists.
                const hidden = fc ? fc.querySelector('input[name], input[type=hidden]') : null;
                return {
                    tag: el.tagName.toLowerCase(),
                    id: el.id || null,
                    name: el.getAttribute('name'),
                    ariaLabelledby: el.getAttribute('aria-labelledby'),
                    ariaLabel: el.getAttribute('aria-label'),
                    label: lbl ? lbl.innerText.trim() : null,
                    hiddenName: hidden ? hidden.getAttribute('name') : null,
                    hiddenId: hidden ? hidden.id : null,
                };
            }""")
            el_id = info["id"]
            rejected = sn._looks_autogenerated(el_id) if el_id else "(no id)"
            print(f"--- dropdown #{i}: label={info['label']!r} ---")
            print(f"    id              = {el_id!r}   (snapshotter discards as autogen? {rejected})")
            print(f"    name            = {info['name']!r}")
            print(f"    aria-labelledby = {info['ariaLabelledby']!r}")
            print(f"    hidden input    = name={info['hiddenName']!r}  id={info['hiddenId']!r}")
            print()


if __name__ == "__main__":
    target = (
        sys.argv[1]
        if len(sys.argv) > 1
        else "http://192.168.0.191:8000/accounting/cash-in/general"
    )
    asyncio.run(main(target))
